services:
  postgres:
    image: postgres:16-alpine
    container_name: volter_db
    environment:
      POSTGRES_USER: volter_user
      POSTGRES_PASSWORD: volter123
      POSTGRES_DB: volter
      TZ: Europe/Skopje
      PGTZ: Europe/Skopje
    ports:
      - "5432:5432"
    volumes:
      - volter_pgdata:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "timezone=Europe/Skopje"
      - "-c"
      - "log_timezone=Europe/Skopje"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U volter_user -d volter"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: volter_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/volter
      SPRING_DATASOURCE_USERNAME: volter_user
      SPRING_DATASOURCE_PASSWORD: volter123
      JWT_CONFIG_SECRET: zXNc4+RJ95DIa5F95Kt2vonGZuaAfAWv+IJDEfPQ/mI=
      ALLOWED_ORIGINS: http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: volter_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  volter_pgdata:
    driver: local
