-- ============================================================
-- Volter :: PER-SHOP (tenant) schema
-- Runs once against EACH shop schema via Flyway.
-- Cross-schema FKs reference the shared `public` schema
-- (public.staff). Same-schema references are unqualified and
-- resolve to the tenant schema (Flyway defaultSchema).
-- ============================================================

-- ----------------------------------------------------------------
-- customer
-- ----------------------------------------------------------------
CREATE TABLE customer
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(255)             NOT NULL,
    national_id     VARCHAR(32)              NOT NULL,
    phone_primary   VARCHAR(32)              NOT NULL,
    phone_secondary VARCHAR(32),
    address         VARCHAR(255)             NOT NULL,
    city            VARCHAR(100)             NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_customer_national_id UNIQUE (national_id)
);

-- ----------------------------------------------------------------
-- item  (single table; type-specific data lives in `attributes`)
-- ----------------------------------------------------------------
CREATE TABLE item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(50)              NOT NULL,
    origin      VARCHAR(50)              NOT NULL,
    status      VARCHAR(50)              NOT NULL,
    description TEXT,
    attributes  JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0
);

-- ----------------------------------------------------------------
-- item_status_history
-- ----------------------------------------------------------------
CREATE TABLE item_status_history
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id             BIGINT                   NOT NULL,
    changed_by_staff_id BIGINT                   NOT NULL, -- changedBy
    from_status         VARCHAR(50),                       -- nullable for initial status
    to_status           VARCHAR(50)              NOT NULL,
    occurred_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_item_status_history_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_item_status_history_staff FOREIGN KEY (changed_by_staff_id) REFERENCES public.staff (id)
);

-- ----------------------------------------------------------------
-- cash_register
-- ----------------------------------------------------------------
CREATE TABLE cash_register
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(64)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cash_register_code UNIQUE (code)
);

-- ----------------------------------------------------------------
-- cash_register_session
-- ----------------------------------------------------------------
CREATE TABLE cash_register_session
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_register_id         BIGINT                       NOT NULL,
    staff_id                 BIGINT                       NOT NULL, -- openedBy / closedBy
    opened_at                TIMESTAMP WITH TIME ZONE     NOT NULL,
    closed_at                TIMESTAMP WITH TIME ZONE,
    opening_balance          INTEGER                      NOT NULL,
    current_balance          INTEGER                      NOT NULL DEFAULT 0, -- running drawer balance, may go negative
    expected_interest        INTEGER                      NOT NULL DEFAULT 0,
    closing_balance          INTEGER,                               -- nullable until session is closed; expected balance is derived from current_balance
    status                   VARCHAR(50)                  NOT NULL,
    version                  BIGINT                       NOT NULL DEFAULT 0,
    CONSTRAINT fk_crs_cash_register FOREIGN KEY (cash_register_id) REFERENCES cash_register (id),
    CONSTRAINT fk_crs_staff FOREIGN KEY (staff_id) REFERENCES public.staff (id)
);

CREATE UNIQUE INDEX uk_crs_open
    ON cash_register_session (cash_register_id)
    WHERE status = 'OPEN';

-- ----------------------------------------------------------------
-- pawn_contract
-- ----------------------------------------------------------------
CREATE TABLE pawn_contract
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         BIGINT                   NOT NULL,
    item_id             BIGINT                   NOT NULL,
    created_by_staff_id BIGINT                   NOT NULL, -- createdBy
    principal_amount    INTEGER                  NOT NULL,
    interest_amount     INTEGER                  NOT NULL,
    term_days           INTEGER                  NOT NULL,
    issue_date          DATE                     NOT NULL,
    due_date            DATE                     NOT NULL,
    original_due_date   DATE                     NOT NULL,
    status              VARCHAR(50)              NOT NULL,
    redeemed_at         TIMESTAMP WITH TIME ZONE,
    forfeited_at        TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_pawn_contract_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_pawn_contract_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_pawn_contract_staff FOREIGN KEY (created_by_staff_id) REFERENCES public.staff (id)
);

CREATE UNIQUE INDEX uk_active_pawn_contract_item
    ON pawn_contract (item_id)
    WHERE status = 'ACTIVE';

-- ----------------------------------------------------------------
-- pawn_contract_extension
-- ----------------------------------------------------------------
CREATE TABLE pawn_contract_extension
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pawn_contract_id  BIGINT                   NOT NULL,
    previous_due_date DATE                     NOT NULL,
    new_due_date      DATE                     NOT NULL,
    interest_paid     INTEGER                  NOT NULL,
    fee               INTEGER                  NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pce_pawn_contract FOREIGN KEY (pawn_contract_id) REFERENCES pawn_contract (id)
);

-- ----------------------------------------------------------------
-- sale
-- ----------------------------------------------------------------
CREATE TABLE sale
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT                   NOT NULL,
    item_id        BIGINT                   NOT NULL,
    created_by_staff_id       BIGINT                   NOT NULL,
    status         VARCHAR(50)              NOT NULL,
    purchase_price INTEGER                  NOT NULL,
    sale_price     INTEGER, -- nullable until sold
    sold_at        TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    version        BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_sale_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_sale_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_sale_staff FOREIGN KEY (created_by_staff_id) REFERENCES public.staff (id)
);

CREATE UNIQUE INDEX uk_available_sale_item
    ON sale (item_id)
    WHERE status = 'AVAILABLE';

-- ----------------------------------------------------------------
-- expense
-- ----------------------------------------------------------------
CREATE TABLE expense
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    BIGINT                   NOT NULL,
    category    VARCHAR(50)              NOT NULL,
    amount      INTEGER                  NOT NULL,
    description TEXT,
    date        DATE                     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_expense_staff FOREIGN KEY (staff_id) REFERENCES public.staff (id)
);

-- ----------------------------------------------------------------
-- transaction  (base ledger entry)
-- ----------------------------------------------------------------
CREATE TABLE transaction
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id                 BIGINT                   NOT NULL,
    cash_register_session_id BIGINT                   NOT NULL,
    type                     VARCHAR(50)              NOT NULL,
    amount                   INTEGER                  NOT NULL,
    direction                VARCHAR(50)              NOT NULL,
    description              TEXT,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transaction_staff FOREIGN KEY (staff_id) REFERENCES public.staff (id),
    CONSTRAINT fk_transaction_crs FOREIGN KEY (cash_register_session_id) REFERENCES cash_register_session (id)
);

-- ----------------------------------------------------------------
-- pawn_transaction  (subtype link: transaction <-> pawn_contract)
-- ----------------------------------------------------------------
CREATE TABLE pawn_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   BIGINT                  NOT NULL,
    pawn_contract_id BIGINT                  NOT NULL,
    action           VARCHAR(50)             NOT NULL,
    CONSTRAINT fk_pawn_tx_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id),
    CONSTRAINT fk_pawn_tx_pawn_contract FOREIGN KEY (pawn_contract_id) REFERENCES pawn_contract (id),
    CONSTRAINT uk_pawn_tx_transaction UNIQUE (transaction_id)
);

-- ----------------------------------------------------------------
-- sale_transaction  (subtype link: transaction <-> sale)
-- ----------------------------------------------------------------
CREATE TABLE sale_transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT                  NOT NULL,
    sale_id        BIGINT                  NOT NULL,
    action         VARCHAR(50)             NOT NULL,
    CONSTRAINT fk_sale_tx_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id),
    CONSTRAINT fk_sale_tx_sale FOREIGN KEY (sale_id) REFERENCES sale (id),
    CONSTRAINT uk_sale_tx_transaction UNIQUE (transaction_id)
);

-- ----------------------------------------------------------------
-- expense_transaction  (subtype link: transaction <-> expense)
-- ----------------------------------------------------------------
CREATE TABLE expense_transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT                     NOT NULL,
    expense_id     BIGINT                     NOT NULL,
    action         VARCHAR(50)                NOT NULL,
    CONSTRAINT fk_expense_tx_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id),
    CONSTRAINT fk_expense_tx_expense FOREIGN KEY (expense_id) REFERENCES expense (id),
    CONSTRAINT uk_expense_tx_transaction UNIQUE (transaction_id)
);

-- ----------------------------------------------------------------
-- cash_register_transaction  (subtype link: transaction <-> register)
-- ----------------------------------------------------------------
CREATE TABLE cash_register_transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT                           NOT NULL,
    action         VARCHAR(50)                      NOT NULL,
    CONSTRAINT fk_cr_tx_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id),
    CONSTRAINT uk_cr_tx_transaction UNIQUE (transaction_id)
);

-- ----------------------------------------------------------------
-- cash_register_session_discrepancy
-- ----------------------------------------------------------------
CREATE TABLE cash_register_session_discrepancy
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_register_session_id BIGINT                                   NOT NULL,
    resolved_by_staff_id     BIGINT,
    expected_amount          INTEGER                                  NOT NULL,
    counted_amount           INTEGER                                  NOT NULL,
    difference               INTEGER                                  NOT NULL,
    type                     VARCHAR(50)                              NOT NULL,
    status                   VARCHAR(50)                              NOT NULL,
    resolution_note          TEXT,
    created_at               TIMESTAMP WITH TIME ZONE                 NOT NULL,
    resolved_at              TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_crsd_session FOREIGN KEY (cash_register_session_id) REFERENCES cash_register_session (id),
    CONSTRAINT fk_crsd_staff FOREIGN KEY (resolved_by_staff_id) REFERENCES public.staff (id)
);
