CREATE TABLE notification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_staff_id BIGINT                   NOT NULL,
    type               VARCHAR(50)              NOT NULL,
    title              VARCHAR(255)             NOT NULL,
    description        TEXT,
    entity_type        VARCHAR(100),
    entity_id          BIGINT,
    is_read            BOOLEAN                  NOT NULL DEFAULT FALSE,
    read_at            TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_staff FOREIGN KEY (recipient_staff_id) REFERENCES public.staff (id)
);
