-- ----------------------------------------------------------------
-- pawn_note
-- Free-form notes staff attach to a pawn contract (a reminder, a call
-- with the client, a condition of the item). A note carries only a
-- description; it is ACTIVE until someone marks it RESOLVED, and can be
-- moved back to ACTIVE.
-- ----------------------------------------------------------------
CREATE TABLE pawn_note
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pawn_contract_id    BIGINT                   NOT NULL,
    created_by_staff_id BIGINT                   NOT NULL,
    description         TEXT                     NOT NULL,
    status              VARCHAR(50)              NOT NULL DEFAULT 'ACTIVE',
    resolved_at         TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pawn_note_pawn_contract FOREIGN KEY (pawn_contract_id) REFERENCES pawn_contract (id),
    CONSTRAINT fk_pawn_note_staff FOREIGN KEY (created_by_staff_id) REFERENCES public.staff (id)
);

-- Notes are always read for one contract at a time, newest first.
CREATE INDEX idx_pawn_note_contract ON pawn_note (pawn_contract_id, created_at DESC);
