-- ----------------------------------------------------------------
-- pawn_contract_event
-- Things that happen to a pawn contract but move no money, so they have
-- no place in the `transaction` ledger (which requires a cash register
-- session and shifts its running balance). Today that means forfeiture:
-- the contract is closed and the item goes up for sale, with no payment.
-- ----------------------------------------------------------------
CREATE TABLE pawn_contract_event
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pawn_contract_id      BIGINT                   NOT NULL,
    action                VARCHAR(50)              NOT NULL,
    performed_by_staff_id BIGINT                   NOT NULL,
    description           TEXT,
    occurred_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pce_event_pawn_contract FOREIGN KEY (pawn_contract_id) REFERENCES pawn_contract (id),
    CONSTRAINT fk_pce_event_staff FOREIGN KEY (performed_by_staff_id) REFERENCES public.staff (id)
);

CREATE INDEX idx_pawn_contract_event_occurred ON pawn_contract_event (occurred_at DESC);
CREATE INDEX idx_pawn_contract_event_contract ON pawn_contract_event (pawn_contract_id);

-- Backfill the forfeits that already happened, so the activity list is not
-- blank for existing contracts. The staff member who did it is taken from the
-- item's IN_SALE status change (the accurate record), falling back to the
-- contract's author when no such history row exists.
INSERT INTO pawn_contract_event (pawn_contract_id, action, performed_by_staff_id, description, occurred_at)
SELECT pc.id,
       'FORFEITED',
       COALESCE((SELECT h.changed_by_staff_id
                   FROM item_status_history h
                  WHERE h.item_id = pc.item_id
                    AND h.to_status = 'IN_SALE'
                  ORDER BY h.occurred_at DESC
                  LIMIT 1),
                pc.created_by_staff_id),
       'Залогот е пренесен во продажба',
       COALESCE(pc.forfeited_at, pc.updated_at)
FROM pawn_contract pc
WHERE pc.status = 'FORFEITED';

-- ----------------------------------------------------------------
-- activity_entry
-- One list for the transactions page: money transactions and the
-- non-monetary pawn events above, in one sortable/filterable relation.
-- `entry_id` prefixes the source id so the two id spaces cannot collide.
-- Events carry no amount, direction or session - those stay NULL, which is
-- what marks a row as "not money" in the UI.
-- ----------------------------------------------------------------
CREATE VIEW activity_entry AS
SELECT 'T' || t.id                     AS entry_id,
       'TRANSACTION'                   AS kind,
       t.id                            AS source_id,
       t.staff_id                      AS staff_id,
       t.cash_register_session_id      AS cash_register_session_id,
       t.type                          AS type,
       t.amount                        AS amount,
       t.direction                     AS direction,
       t.description                   AS description,
       t.created_at                    AS occurred_at
FROM transaction t
UNION ALL
SELECT 'E' || e.id,
       'PAWN_EVENT',
       e.id,
       e.performed_by_staff_id,
       NULL,
       'PAWN_' || e.action,
       NULL,
       NULL,
       e.description,
       e.occurred_at
FROM pawn_contract_event e;
