-- ============================================================
-- Volter :: PUBLIC schema (shared / identity context)
-- Runs once against the `public` schema via Flyway.
-- Per-shop schemas reference these tables across schemas.
-- ============================================================

-- ----------------------------------------------------------------
-- shop
-- ----------------------------------------------------------------
CREATE TABLE shop
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)             NOT NULL,
    code        VARCHAR(64)              NOT NULL,
    schema_name VARCHAR(63)              NOT NULL, -- because PostgreSQL schema names have a max length of 63 characters
    address     VARCHAR(255),
    phone       VARCHAR(32),
    status      VARCHAR(50)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_shop_code UNIQUE (code),
    CONSTRAINT uk_shop_schema_name UNIQUE (schema_name)
);

-- ----------------------------------------------------------------
-- staff  (merges former IdentityUser + per-shop Staff)
-- ----------------------------------------------------------------
CREATE TABLE staff
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(255)             NOT NULL,
    username        VARCHAR(100)             NOT NULL,
    password_hash   VARCHAR(255)             NOT NULL,
    national_id     VARCHAR(32)              NOT NULL,
    phone_primary   VARCHAR(32)              NOT NULL,
    phone_secondary VARCHAR(32),
    base_salary     INTEGER                  NOT NULL,
    bonus_percent   NUMERIC(5, 2)            NOT NULL,
    status          VARCHAR(50)              NOT NULL,
    manager_id      BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    version         BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_staff_username UNIQUE (username),
    CONSTRAINT uk_staff_national_id UNIQUE (national_id),
    CONSTRAINT fk_staff_manager FOREIGN KEY (manager_id) REFERENCES staff (id)
);

-- ----------------------------------------------------------------
-- role
-- ----------------------------------------------------------------
CREATE TABLE role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_role_name UNIQUE (name)
);

-- ----------------------------------------------------------------
-- permission
-- ----------------------------------------------------------------
CREATE TABLE permission
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)             NOT NULL,
    category   VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_permission_name UNIQUE (name)
);

-- ----------------------------------------------------------------
-- role_permission  (role <-> permission, many-to-many)
-- ----------------------------------------------------------------
CREATE TABLE role_permission
(
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------
-- staff_role  (staff role assignment, scoped per shop)
-- ----------------------------------------------------------------
CREATE TABLE staff_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id   BIGINT                   NOT NULL,
    role_id    BIGINT                   NOT NULL,
    shop_id    BIGINT                   NOT NULL,
    status     VARCHAR(50)              NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_staff_role_shop UNIQUE (staff_id, role_id, shop_id),
    CONSTRAINT fk_staff_role_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_role_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_staff_role_shop FOREIGN KEY (shop_id) REFERENCES shop (id)
);

-- ----------------------------------------------------------------
-- staff_shop  (staff <-> shop assignment)
-- ----------------------------------------------------------------
CREATE TABLE staff_shop
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id      BIGINT                   NOT NULL,
    shop_id       BIGINT                   NOT NULL,
    status        VARCHAR(50)              NOT NULL,
    assigned_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    unassigned_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_staff_shop UNIQUE (staff_id, shop_id),
    CONSTRAINT fk_staff_shop_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_shop_shop FOREIGN KEY (shop_id) REFERENCES shop (id)
);

-- ----------------------------------------------------------------
-- auth_event
-- ----------------------------------------------------------------
CREATE TABLE auth_event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    BIGINT                   NOT NULL,
    type        VARCHAR(50)              NOT NULL,
    ip_address  VARCHAR(64),
    user_agent  VARCHAR(512),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_auth_event_staff FOREIGN KEY (staff_id) REFERENCES staff (id)
);

-- ----------------------------------------------------------------
-- notification
-- ----------------------------------------------------------------
CREATE TABLE notification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_staff_id BIGINT                   NOT NULL,
    shop_id            BIGINT,
    type               VARCHAR(50)              NOT NULL,
    title              VARCHAR(255)             NOT NULL,
    description        TEXT,
    entity_type        VARCHAR(100),
    entity_id          BIGINT,
    is_read            BOOLEAN                  NOT NULL DEFAULT FALSE,
    read_at            TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_staff FOREIGN KEY (recipient_staff_id) REFERENCES staff (id),
    CONSTRAINT fk_notification_shop FOREIGN KEY (shop_id) REFERENCES shop (id)
);

-- ----------------------------------------------------------------
-- report
-- ----------------------------------------------------------------
CREATE TABLE report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id          BIGINT                   NOT NULL,
    owner_staff_id   BIGINT,
    subject_staff_id BIGINT,
    type             VARCHAR(50)              NOT NULL,
    date_from        DATE                     NOT NULL,
    date_to          DATE                     NOT NULL,
    payload          JSONB,
    generated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_report_shop FOREIGN KEY (shop_id) REFERENCES shop (id),
    CONSTRAINT fk_report_staff_owner FOREIGN KEY (owner_staff_id) REFERENCES staff (id),
    CONSTRAINT fk_report_staff_subject FOREIGN KEY (subject_staff_id) REFERENCES staff (id)
);
