package com.volter.platform.modules.report.domain.model;

import com.volter.platform.modules.report.domain.model.enums.ReportType;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * A generated report (e.g. a monthly summary or staff-performance report) for a
 * shop and date range. The computed figures are stored as an opaque JSON
 * {@code payload}; staff references are kept by id (identity context).
 */
@Entity
@Table(schema = "public", name = "report")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class Report {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull(message = "Shop is required")
    @Column(name = "shop_id", nullable = false)
    private Long shopId;

    // Who generated the report (the staff member who requested it). Can be null if generated by a system process.
    @Column(name = "owner_staff_id")
    private Long ownerStaffId;

    // The staff member the report is about (e.g. for a staff-performance report). Can be null if the report is about the shop as a whole.
    @Column(name = "subject_staff_id")
    private Long subjectStaffId;

    @NotNull(message = "Report type is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 50)
    private ReportType type;

    @NotNull(message = "Report start date is required")
    @Column(name = "date_from", nullable = false)
    private LocalDate dateFrom;

    @NotNull(message = "Report end date is required")
    @Column(name = "date_to", nullable = false)
    private LocalDate dateTo;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", columnDefinition = "jsonb")
    private Map<String, Object> payload;

    @CreationTimestamp
    @Column(name = "generated_at", nullable = false)
    private OffsetDateTime generatedAt;

    public boolean covers(LocalDate date) {
        return !date.isBefore(dateFrom) && !date.isAfter(dateTo);
    }

    public boolean isVisibleTo(Long staffId) {
        return ownerStaffId == null || ownerStaffId.equals(staffId);
    }

    /**
     * A shop-wide monthly summary generated by the system: no owner (it's a system
     * report visible to everyone in the shop) and no subject (it's about the whole shop).
     */
    public static Report systemMonthlySummary(Long shopId, LocalDate from, LocalDate to, Map<String, Object> payload) {
        return Report.builder()
                .shopId(shopId)
                .ownerStaffId(null)
                .subjectStaffId(null)
                .type(ReportType.MONTHLY_SUMMARY)
                .dateFrom(from)
                .dateTo(to)
                .payload(payload)
                .build();
    }
}
