SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET search_path TO public;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE shop
(
    id       bigint NOT NULL,
    name     character varying(100),
    city     character varying(20),
    location character varying(20)
);

INSERT INTO shop (id, name, city, location)
VALUES (0, 'Main Shop', 'Skopje', 'Center');

ALTER TABLE shop
    OWNER TO postgres;

ALTER TABLE shop
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME shop_id_seq
        START WITH 1
        INCREMENT BY 1
        MINVALUE 1
        NO MAXVALUE
        CACHE 1
        );

CREATE TABLE cash_register
(
    shop_id          integer                  DEFAULT 0 NOT NULL,
    num_pawns        bigint                   DEFAULT 0 NOT NULL,
    money_pawns      bigint                   DEFAULT 0,
    num_sale_items   bigint                   DEFAULT 0,
    money_sale_items bigint                   DEFAULT 0,
    register_money   bigint                   DEFAULT 0,
    last_updated     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    gold_grams       numeric(7, 3)            DEFAULT 0.0,
    total_provision  bigint                   DEFAULT 0
);


ALTER TABLE cash_register
    OWNER TO postgres;

INSERT INTO cash_register DEFAULT
VALUES;


CREATE TABLE client
(
    id          bigint NOT NULL,
    name        character varying(100),
    embg        character(13),
    telephone   character(20),
    telephone_2 character(20),
    city        character varying(20)
);

ALTER TABLE client
    OWNER TO postgres;

-- Change to BY DEFAULT so we can explicitly insert id = 0
ALTER TABLE client
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME client_id_seq
        START WITH 1
        INCREMENT BY 1
        MINVALUE 1
        NO MAXVALUE
        CACHE 1
        );

-- Insert admin client with id 0
INSERT INTO client (id, name, embg, telephone, telephone_2, city)
VALUES (0, 'Admin', 000, '', '', 'Skopje');

-- Adjust the sequence to continue correctly
SELECT setval('client_id_seq', 1, false);


CREATE TABLE electronics_pawn
(
    shop_id         integer,
    id              integer NOT NULL,
    client_id       integer NOT NULL,
    brand           character varying(50),
    year            integer,
    price_pawned    bigint,
    price_to_redeem bigint,
    provision       bigint,
    date_from       date,
    date_to         date,
    total_days      integer,
    description     character varying(300)
);


ALTER TABLE electronics_pawn
    OWNER TO postgres;

ALTER TABLE electronics_pawn
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME electronics_pawn_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE expense
(
    shop_id     integer,
    year        integer,
    month       integer,
    rent        bigint,
    salaries    bigint,
    other       bigint,
    description character varying(300),
    bills       bigint
);


ALTER TABLE expense
    OWNER TO postgres;

CREATE TABLE gold_pawn
(
    shop_id         integer,
    id              integer NOT NULL,
    client_id       integer NOT NULL,
    weight          numeric(7, 3),
    carats          integer,
    price_pawned    bigint,
    price_to_redeem bigint,
    provision       bigint,
    date_from       date,
    date_to         date,
    total_days      integer,
    description     character varying(300),
    type            character varying(300)
);


ALTER TABLE gold_pawn
    OWNER TO postgres;

ALTER TABLE gold_pawn
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME gold_pawn_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE monthly_report
(
    shop_id                  integer,
    year                     integer NOT NULL,
    month                    integer NOT NULL,
    money_given              bigint,
    money_got                bigint,
    total_turnover           bigint,
    total_pawns              integer,
    num_gold_pawns           integer,
    num_electronics_pawns    integer,
    num_vehicle_pawns        integer,
    num_watch_pawns          integer,
    num_other_pawns          integer,
    money_gold_pawns         bigint,
    money_electronics_pawns  bigint,
    money_vehicle_pawns      bigint,
    money_watch_pawns        bigint,
    money_other_pawns        bigint,
    total_sales              integer,
    money_sales              bigint,
    money_pawns              bigint,
    net_profit               bigint,
    gross_profit             bigint,
    profit_electronics_pawns bigint,
    profit_gold_pawns        bigint,
    profit_vehicle_pawns     bigint,
    profit_watch_pawns       bigint,
    profit_other_pawns       bigint,
    profit_sales             bigint,
    profit_pawns             bigint
);


ALTER TABLE monthly_report
    OWNER TO postgres;

CREATE TABLE other_pawn
(
    shop_id         integer,
    id              integer NOT NULL,
    client_id       integer NOT NULL,
    price_pawned    bigint,
    price_to_redeem bigint,
    provision       bigint,
    date_from       date,
    date_to         date,
    total_days      integer,
    description     character varying(300)
);


ALTER TABLE other_pawn
    OWNER TO postgres;

ALTER TABLE other_pawn
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME other_pawn_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE sale
(
    shop_id      integer,
    id           integer NOT NULL,
    price_bought bigint,
    date_from    date,
    description  character varying(300)
);


ALTER TABLE sale
    OWNER TO postgres;

ALTER TABLE sale
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME sale_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE transaction
(
    shop_id     integer,
    id          bigint NOT NULL,
    client_id   bigint NOT NULL,
    money_given bigint,
    money_got   bigint,
    money_diff  bigint,
    profit      bigint,
    date        timestamp with time zone,
    category    character varying(20),
    description character varying(200)
);


ALTER TABLE transaction
    OWNER TO postgres;

ALTER TABLE transaction
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME transaction_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE vehicle_pawn
(
    shop_id         integer,
    id              integer NOT NULL,
    client_id       integer NOT NULL,
    brand           character varying(50),
    model           character varying(50),
    year            integer,
    price_pawned    bigint,
    price_to_redeem bigint,
    provision       bigint,
    date_from       date,
    date_to         date,
    total_days      integer,
    description     character varying(300)
);


ALTER TABLE vehicle_pawn
    OWNER TO postgres;

ALTER TABLE vehicle_pawn
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME vehicle_pawn_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE watch_pawn
(
    shop_id         integer,
    id              integer NOT NULL,
    client_id       integer NOT NULL,
    brand           character varying(50),
    year            integer,
    price_pawned    bigint,
    price_to_redeem bigint,
    provision       bigint,
    date_from       date,
    date_to         date,
    total_days      integer,
    description     character varying(300)
);


ALTER TABLE watch_pawn
    OWNER TO postgres;

ALTER TABLE watch_pawn
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME watch_pawn_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


CREATE TABLE yearly_report
(
    shop_id                 integer,
    year                    integer NOT NULL,
    money_given             bigint,
    money_got               bigint,
    total_turnover          bigint,
    total_profit            bigint,
    total_pawns             integer,
    num_gold_pawns          integer,
    num_electronics_pawns   integer,
    num_vehicle_pawns       integer,
    num_watch_pawns         integer,
    num_other_pawns         integer,
    money_pawns             bigint,
    money_gold_pawns        bigint,
    money_electronics_pawns bigint,
    money_vehicle_pawns     bigint,
    money_watch_pawns       bigint,
    money_other_pawns       bigint,
    total_sales             integer,
    money_sales             bigint
);

ALTER TABLE yearly_report
    OWNER TO postgres;

------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE ONLY shop
    ADD CONSTRAINT shop_pkey PRIMARY KEY (id);


ALTER TABLE ONLY cash_register
    ADD CONSTRAINT cash_register_pkey PRIMARY KEY (num_pawns);


ALTER TABLE ONLY client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


ALTER TABLE ONLY electronics_pawn
    ADD CONSTRAINT electronics_pawn_pkey PRIMARY KEY (id);


ALTER TABLE ONLY gold_pawn
    ADD CONSTRAINT gold_pawn_pkey PRIMARY KEY (id);


ALTER TABLE ONLY monthly_report
    ADD CONSTRAINT monthly_report_pkey PRIMARY KEY (year, month);


ALTER TABLE ONLY other_pawn
    ADD CONSTRAINT other_pawn_pkey PRIMARY KEY (id);


ALTER TABLE ONLY sale
    ADD CONSTRAINT sale_pkey PRIMARY KEY (id);


ALTER TABLE ONLY transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


ALTER TABLE ONLY client
    ADD CONSTRAINT unique_client UNIQUE (name, embg, telephone);


ALTER TABLE ONLY vehicle_pawn
    ADD CONSTRAINT vehicle_pawn_pkey PRIMARY KEY (id);


ALTER TABLE ONLY watch_pawn
    ADD CONSTRAINT watch_pawn_pkey PRIMARY KEY (id);


ALTER TABLE ONLY yearly_report
    ADD CONSTRAINT yearly_report_pkey PRIMARY KEY (year);


------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------


ALTER TABLE ONLY electronics_pawn
    ADD CONSTRAINT electronics_pawn_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT electronics_pawn_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY gold_pawn
    ADD CONSTRAINT gold_pawn_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT gold_pawn_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY other_pawn
    ADD CONSTRAINT other_pawn_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT other_pawn_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY vehicle_pawn
    ADD CONSTRAINT vehicle_pawn_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT vehicle_pawn_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY watch_pawn
    ADD CONSTRAINT watch_pawn_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT watch_pawn_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY sale
    ADD CONSTRAINT sale_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY transaction
    ADD CONSTRAINT transaction_client_id_fkey FOREIGN KEY (client_id) REFERENCES client (id),
    ADD CONSTRAINT transaction_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY expense
    ADD CONSTRAINT expense_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY monthly_report
    ADD CONSTRAINT monthly_report_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY yearly_report
    ADD CONSTRAINT yearly_report_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);


ALTER TABLE ONLY cash_register
    ADD CONSTRAINT cash_register_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shop (id);
